# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "0.0.0.0" # the base hostname & protocol for your site


# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Enrique Catalá
  #avatar: avatar.png
  avatar: enrique.jpg
  gravatar: # Email MD5 hash
  description: "Enrique Catala Bañuls portfolio" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Data engineering with Enrique Catalá</h1>
  header_text_feature_image: 
  footer_text: >
    Subscribe to my channel! <script src="https://apis.google.com/js/platform.js"></script><div class="g-ytsubscribe" data-channelid="UCYboHnN6tvFfHqPWZWY82AQ" data-layout="default" data-count="default"></div>   
  #Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://github.com/rohanchandra/type-theme/">Portfolio-iro</a> <script src="https://apis.google.com/js/platform.js"></script><div class="g-ytsubscribe" data-channelid="UCYboHnN6tvFfHqPWZWY82AQ" data-layout="default" data-count="default"></div>
  # Icons
  rss: false
  email_address: "enrique@enriquecatala.com"
  behance:
  bitbucket:
  #dribbble: ""
  #facebook: "enriquecatala"
  flickr:
  #github: "madebymunsters/type-theme"
  github: "enriquecatala"
  #google_plus:
  #instagram: "enriquecatala"
  linkedin:  "https://www.linkedin.com/in/enriquecatala/"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "enriquecatala"
  wordpress:
  youtube: "enriquecatala"

  # Scripts
  google_analytics: UA-169893411-1
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true

# BUILD SETTINGS
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed

plugins: [jekyll-paginate]

# Tipue search settings
tipue_search:
  include:
    pages: true
    collections: [posts]
  exclude:
    files: [search.html]
